//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataOne.BitUp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataOne.BitUp.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  has changed! Starting to clone....
        /// </summary>
        internal static string CloneRepository {
            get {
                return ResourceManager.GetString("CloneRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloning wiki....
        /// </summary>
        internal static string CloneWiki {
            get {
                return ResourceManager.GetString("CloneWiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error cloning repository: .
        /// </summary>
        internal static string CloningError {
            get {
                return ResourceManager.GetString("CloningError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting issues....
        /// </summary>
        internal static string ExportIssues {
            get {
                return ResourceManager.GetString("ExportIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error exporting issues: .
        /// </summary>
        internal static string IssueExportingError {
            get {
                return ResourceManager.GetString("IssueExportingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  has not changed since last backup! Last backup was at .
        /// </summary>
        internal static string RepositoryNotChanged {
            get {
                return ResourceManager.GetString("RepositoryNotChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storing file: .
        /// </summary>
        internal static string StoreFile {
            get {
                return ResourceManager.GetString("StoreFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error storing file: .
        /// </summary>
        internal static string StoringError {
            get {
                return ResourceManager.GetString("StoringError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error cloning wiki: .
        /// </summary>
        internal static string WikiCloningError {
            get {
                return ResourceManager.GetString("WikiCloningError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Putting files into zip....
        /// </summary>
        internal static string Zipping {
            get {
                return ResourceManager.GetString("Zipping", resourceCulture);
            }
        }
    }
}
